### ISSUE TITLE
Add /Contents/Resources/ to possible icon paths

### ISSUE THREAD

**Issue by ThatIsAPseudo** [mklement0/fileicon#26]
Many apps store their icon in the `/Contents/Resources/` folder, so `fileicon get` should also look up there in case it doesn't find any `Icon\r` file.

![Example image](https://user-images.githubusercontent.com/17936055/118294224-08440100-b4ca-11eb-8acd-9c0e03eb1d68.png)

**Comment by mklement0** [comment]
Thanks for the suggestion, but:

* this _convention_ is specific to `.app` bundles, which are _specialized_ folder (structures)
* _multiple_ icon files are often present.

And since these files are readily available for direct copying, you don't need a tool such as `fileget` for it.

By contrast, `fileget` is focused on managing the not-readily-accessible _metadata_-based icon information associated with a file or folder, representing the file/folder _itself_.
