### ISSUE TITLE
Volume support

### ISSUE THREAD

**Issue by neersighted** [mklement0/fileicon#35]
Volumes can have a custom icon set by creating `/.VolumeIcon.icns`, where `/` represents the volume root. Currently fileicon will set volume icons as it uses AppleScript, but it will return an error as it is not aware of how to read back a volume's icon.

**Comment by mklement0** [comment]
Thanks, @neersighted - sorry it took me so long to respond.

Given a folder path, how can you tell whether it is a volume mount point?

Or are all volumes mount points invariably?  by convention? are subfolders of `/Volumes`?

**Comment by mklement0** [comment]
@neersighted, I've just published `v0.3.2`, which adds support for volumes _in pirinciple_.

However, as of macOS 13.1 (Ventura), I see _inconsistent_ support for assigning icons to volumes,
for which I have no explanation:

The underlying Cocoa API call _mostly_ only *half* succeeds: 

It creates the `.VolumeIcon.icns` helper file, but quietly fails to set the custom-icon flag in the 
`com.apple.FinderInfo` extended attribute of the mountpoint folder.

See [this Ask Different question](https://apple.stackexchange.com/q/451965/28668) question for how others are experiencing similar problems.

The read-me now contains a warning about the lack of predictable support.

I'm closing this, due to `v0.3.2` now trying the best it can to support volume icons, but if you have insights on how to make the support more predictable, I encourage you to open a new issue.
